---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Restart containerd and kubelet
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: yes
  loop:
    - containerd
    - kubelet