---
- name: Setup Common settings on all nodes
  hosts: k8s_cluster
  become: true
  roles:
    - role: base-os-setup
    - role: user-management
    - role: k8s-node-common

- name: Setup Master specific settings
  hosts: k8s_controle_plane
  become: true
  roles:
    - role: k8s-controle-plane

- name: Setup Worker specific settings
  hosts: k8s_worker
  become: true
  roles:
    - role: k8s-worker
