
---
- name: Setup Common settings on all nodes
  hosts: k8s_cluster
  become: yes
  handlers:
    - name: Restart containerd
      ansible.builtin.systemd:
        name: containerd
        state: restarted
        daemon_reload: yes

    - name: Restart kubelet
      ansible.builtin.systemd:
        name: kubelet
        state: restarted
        daemon_reload: yes
  roles:
    - role: common

- name: Setup Master specific settings
  hosts: masters
  become: yes
  roles:
    - role: master

- name: Setup Worker specific settings
  hosts: workers
  become: yes
  roles:
    - role: worker

