---
- name: Setup Common settings on all nodes
  hosts: k8s_cluster
  become: true
  roles:
    - role: base-os-setup
    - role: user-management
    - role: k8s-node-common

- name: Setup Master specific settings
  hosts: k8s_control_plane
  become: true
  roles:
    - role: k8s-control-plane
    - role: cni-cilium

- name: Setup Worker specific settings
  hosts: k8s_worker
  become: true
  roles:
    - role: k8s-worker

- name: Setup GPU Node specific settings
  hosts: gpu_nodes
  become: true
  tags: 
    - gpu_setup
  vars:
    container_runtime: containerd
  roles:
    - role: gpu-node-setup

- name: Deploy Foundational Add-ons
  hosts: k8s_control_plane[0]
  become: true
  environment:
    KUBECONFIG: "{{ playbook_dir }}/.kube/config"
  roles:
    - role: argocd
