---
# ===================================================================
# ステップ 3.1 & 3.2: NVIDIA Container Toolkitのインストール
# ===================================================================
- name: "【最終手段・修正版】成功実績のある公式スクリプトを直接実行してリポジトリを設定"
  ansible.builtin.shell: |
    set -e
    distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
    keyring_path="/etc/apt/keyrings/nvidia-container-toolkit-keyring.gpg"
    list_path="/etc/apt/sources.list.d/nvidia-container-toolkit.list"

    # GPGキーをダウンロード・配置
    curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o "${keyring_path}"

    # リポジトリリストをダウンロードし、署名キー情報を追記して配置
    curl -s -L "https://nvidia.github.io/libnvidia-container/${distribution}/libnvidia-container.list" | \
      sed "s#deb https://#deb [signed-by=${keyring_path}] https://#g" > "${list_path}"

    # aptキャッシュを更新
    apt-get update
  args:
    # このスクリプトは、以下のファイルが存在しない場合のみ実行される (冪等性の確保)
    creates: /etc/apt/sources.list.d/nvidia-container-toolkit.list
  become: true

- name: "nvidia-container-toolkit をインストール"
  ansible.builtin.apt:
    name: "nvidia-container-toolkit"
    state: present
  become: true

# ===================================================================
# ステップ 3.3: containerd の設定
# ===================================================================
- name: "containerdにNVIDIAランタイムを設定 (nvidia-ctk)"
  ansible.builtin.command: "nvidia-ctk runtime configure --runtime=containerd"
  register: ctk_configure
  changed_when: "'The NVIDIA Container Runtime is already configured' not in ctk_configure.stderr"
  notify: Restart containerd and kubelet

- name: "containerdのデフォルトランタイムを 'nvidia' に変更"
  ansible.builtin.lineinfile:
    path: "/etc/containerd/config.toml"
    # [plugins."io.containerd.grpc.v1.cri".containerd] セクション内の default_runtime_name を探す
    regexp: '^( *default_runtime_name *= *).*$'
    line: '\1"nvidia"' # 見つけた行の "runc" 等を "nvidia" に置換
    backrefs: yes # regexp のキャプチャグループ (\1) を使う
  notify: Restart containerd and kubelet

- name: "GPUノードにDevice Plugin用の必須ラベルを付与"
  ansible.builtin.command: "kubectl label node {{ inventory_hostname }} nvidia.com/gpu.present=true --overwrite"
  register: command_result
  changed_when: "'labeled' in command_result.stdout"
  # すでにラベルが存在する場合はエラーになるが、処理は成功とみなす
  failed_when: command_result.rc != 0 and 'AlreadyExists' not in command_result.stderr
  delegate_to: "{{ groups['k8s_control_plane'][0] }}"
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"
  become: false 
# ===================================================================
# NVIDIA Kubernetes Device Plugin のデプロイ (変更なし)
# ===================================================================
- name: "Block for NVIDIA Device Plugin Deployment (Run Once)"
  block:
    - name: Add NVIDIA Helm repository
      community.kubernetes.helm_repository:
        name: nvdp
        repo_url: "https://nvidia.github.io/k8s-device-plugin"
        state: present

    - name: Deploy NVIDIA Device Plugin using Helm
      community.kubernetes.helm:
        name: nvdp-plugin
        chart_ref: nvdp/nvidia-device-plugin
        release_namespace: nvidia-device-plugin
        create_namespace: yes
        state: present
        update_repo_cache: yes
  run_once: true
  delegate_to: "{{ groups['k8s_control_plane'][0] }}"
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"