---
- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    daemon_reload: true
  listen: "Restart containerd"

- name: Restart kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
  listen: "Restart kubelet"
